### PR TITLE
fix: MLX scalar item bit width bug

### LINKED ISSUE #70: Always grey images when using Stable Diffusion with Bumblebee
I have a MacBook with M3 Pro and I'm trying to utilize GPU for Neural Network tasks with LiveBook & Bumblebee.

DistillBERT (question answering) works fine, but when I try to use "text-to-image" I always get results like this.

Screenshot 2024-12-29 at 15 32 59

But if use 3090 RTX via EXLA and the _same_ model with the _same_ settings I get normal images.

I'm using LiveBook. My setup:

```elixir
Mix.install(
  [
    {:kino_bumblebee, "~> 0.5.0"},
    {:emlx, github: "elixir-nx/emlx"}
  ],
  config: [nx: [default_backend: {EMLX.Backend, device: :cpu}]],
  system_env: []
)
```

And Bumble-related codeblocks:

```elixir
Nx.Defn.default_options(compiler: EMLX)

repository_id = "CompVis/stable-diffusion-v1-4"
{:ok, tokenizer} = Bumblebee.load_tokenizer({:hf, "openai/clip-vit-large-patch14"})
{:ok, clip} = Bumblebee.load_model({:hf, repository_id, subdir: "text_encoder"})
{:ok, unet} = Bumblebee.load_model({:hf, repository_id, subdir: "unet"})

{:ok, vae} =
  Bumblebee.load_model({:hf, repository_id, subdir: "vae"}, architecture: :decoder)

{:ok, scheduler} = Bumblebee.load_scheduler({:hf, repository_id, subdir: "scheduler"})

{:ok, featurizer} =
  Bumblebee.load_featurizer({:hf, repository_id, subdir: "feature_extractor"})

{:ok, safety_checker} =
  Bumblebee.load_model({:hf, repository_id, subdir: "safety_checker"})

serving =
  Bumblebee.Diffusion.StableDiffusion.text_to_image(clip, unet, vae, tokenizer, scheduler,
    num_steps: 40,
    num_images_per_prompt: 1,
    safety_checker: safety_checker,
    safety_checker_featurizer: featurizer,
    compile: [batch_size: 1, sequence_length: 50]
  )
```

And UI:

```elixir
text_input =
  Kino.Input.textarea("Text",
    default: "numbat, forest, high quality, detailed, digital art"
  )

seed_input = Kino.Input.number("Seed")
form = Kino.Control.form([text: text_input, seed: seed_input], submit: "Run")
frame = Kino.Frame.new()

Kino.listen(form, fn %{data: %{text: text, seed: seed}} ->
  Kino.Frame.render(frame, Kino.Text.new("Running..."))
  output = Nx.Serving.run(serving, %{prompt: text, seed: seed})

  for result <- output.results do
    Kino.Image.new(result.image)
  end
  |> Kino.Layout.grid(columns: 2)
  |> then(&Kino.Frame.render(frame, &1))
end)

Kino.Layout.grid([form, frame], boxed: true, gap: 16)
```

I've tried:

* enabling/disabling `LIBMLX_ENABLE_JIT`
* installing XCode instead of command line tools
* enabling `LIBMLX_BUILD` and build from sources
* updating MacOS from 14 to 15
* changing number of steps. Either black, grey or very-very blurred results.

My main concern:

I'm newbie to NN world. So I want reliable environment for learning & experimenting. And I want to avoid Python when I can and use LiveBook. I have set it up on my Linux PC with Nvidia GPU and it works well. With MacOS I was able to run ollama with big models, use BERT in LiveBook, but image generation doesn't work. I spent 10+ hours trying to fix it and this issue is manifestation of my despair =)

### PR DESCRIPTION
**Pull request by polvalente**
With Nx.Defn.Evaluator's debugging features from Nx 0.10 I was able to track this down.
This was the last mile for getting Stable Diffusion to generate a valid image, tested by running
the issue's script as a standalone exs script.

output

closes #70 (finally!)

Test script to be placed at the root of emlx

```elixir
Mix.install([
   {:bumblebee, github: "elixir-nx/bumblebee", override: true},
  {:emlx, path: __DIR__},
  {:stb_image, "~> 0.1"},
  {:kino_bumblebee, "~> 0.5.1"}
])

Nx.global_default_backend({EMLX.Backend, device: :gpu})

repository_id = "CompVis/stable-diffusion-v1-4"
{:ok, tokenizer} = Bumblebee.load_tokenizer({:hf, "openai/clip-vit-large-patch14"})
{:ok, clip} = Bumblebee.load_model({:hf, repository_id, subdir: "text_encoder"})
{:ok, unet} = Bumblebee.load_model({:hf, repository_id, subdir: "unet"})

{:ok, vae} =
  Bumblebee.load_model({:hf, repository_id, subdir: "vae"}, architecture: :decoder)

{:ok, scheduler} = Bumblebee.load_scheduler({:hf, repository_id, subdir: "scheduler"})

{:ok, featurizer} =
  Bumblebee.load_featurizer({:hf, repository_id, subdir: "feature_extractor"})

{:ok, safety_checker} =
  Bumblebee.load_model({:hf, repository_id, subdir: "safety_checker"})

serving =
  Bumblebee.Diffusion.StableDiffusion.text_to_image(clip, unet, vae, tokenizer, scheduler,
    num_steps: 40,
    num_images_per_prompt: 1,
    safety_checker: safety_checker,
    safety_checker_featurizer: featurizer,
    compile: [batch_size: 1, sequence_length: 50]
  )

IO.puts("running...")
%{results: [%{image: tensor}]} = Nx.Serving.run(serving, %{prompt: "numbat, forest, high quality, detailed, digital art", seed: 1})

tensor |> StbImage.from_nx() |> StbImage.write_file("/tmp/output.png")
```

### CODE REVIEW

File: c_src/emlx_nif.cpp [hunk 1]
```diff
@@ -911,14 +911,53 @@ NIF(isclose) {
...
   TENSOR_PARAM(0, t);
   mlx::core::eval(*t);
-  auto dtype_kind = mlx::core::kindof(t->dtype());
 
-  if (dtype_kind == mlx::core::Dtype::Kind::u ||
-      dtype_kind == mlx::core::Dtype::Kind::i ||
-      dtype_kind == mlx::core::Dtype::Kind::b) {
+  // Fix for MLX scalar layout bug: Use the correct type when calling item<T>()
+  // to avoid reading wrong number of bytes from potentially invalid memory
+  // layouts. See: MLX_BUG_REPORT.md for details on the upstream issue.
```
Comment (polvalente) [inline c_src/emlx_nif.cpp]:
```suggestion
  // layouts.
```
